#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
/usr/lib/polkit-kde-authentication-agent-1 &
$HOME/.config/polybar/launch.sh

bspc monitor -d main browser code discord other empty

bspc config border_width         2
bspc config focused_border_color \#70a2ff
bspc config window_gap          8

bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a firefox desktop='^2'
bspc rule -a gwenview state=fullscreen
bspc rule -a discord desktop='^4'
bspc rule -a dolphin state=floating
bspc rula -a qt6ct state=floating
